# Generated by Django 4.1.6 on 2023-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='local',
            field=models.ManyToManyField(to='atracoes.local'),
        ),
    ]
