# Generated by Django 4.1.6 on 2023-02-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracao',
            new_name='Local',
        ),
    ]
